### ISSUE TITLE
deploy enclave-cc failed

### ISSUE THREAD

**Issue by reclock** [confidential-containers/enclave-cc#379]
I have a machine that supports SGX and wanted to install enclave cc, but it failed 
1.  I installed the program 
![image](https://github.com/confidential-containers/enclave-cc/assets/23696606/c8ad3f61-1461-43dd-8e07-eac0ed1bac37)

2. When I am executing "kubectl apply -k github.com/confidential-containers/operator/config/samples/enclave-cc/hw?ref=v0.7.0", 
![image](https://github.com/confidential-containers/enclave-cc/assets/23696606/c834fd0a-cd18-40fd-a6df-af72c05709d6)

but I can't see the enclave_cc runtime

Is there any problem with my installation?

**Comment by mythi** [comment]
there's not enough information to answer your question but most likely: yes. what's the status of the operator pods?

**Comment by reclock** [comment]
Currently, I have installed enclave cc normally and uploaded the encrypted image to my private repository. However, errors may occur during deployment and use
![image](https://github.com/confidential-containers/enclave-cc/assets/23696606/4d000e9f-3b50-49eb-8f7c-ee2d2725c965)


this is my yaml
```

apiVersion: v1
kind: Pod
metadata:
  name: enclave-cc-pod-test
spec:
  containers:
  - image: 192.168.6.105:8443/rongan/sgxt1:encrypted
    name: hello-world
    workingDir: "/run/rune/boot_instance/"
    env:
    - name: OCCLUM_RELEASE_ENCLAVE
      value: "1"
    command:
    - /run/rune/boot_instance/build/bin/occlum-run
    - /bin/hello_world
  runtimeClassName: enclave-cc
```
