### ISSUE TITLE
how to configure image decryption keys

### ISSUE THREAD

**Issue by reclock** [confidential-containers/enclave-cc#391]
yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: enclave-cc-pod-test
spec:
  containers:
  - image: ghcr.io/confidential-containers/test-container-enclave-cc:encrypted
    name: hello-world
    workingDir: "/run/rune/boot_instance/"
    env:
    - name: OCCLUM_RELEASE_ENCLAVE
      value: "1"
    command:
    - /run/rune/boot_instance/build/bin/occlum-run
    - /bin/hello_world
  runtimeClassName: enclave-cc

```

error:

![image](https://github.com/confidential-containers/enclave-cc/assets/23696606/2271e431-5bd9-465a-8664-4bf7c41fef57)
