### ISSUE TITLE
The FIO test reported an "Out of TCS" error.

### ISSUE THREAD

**Issue by zzzqwqw** [confidential-containers/enclave-cc#514]
I conducted FIO testing (test code: https://github.com/axboe/fio) inside a container running with the enclave-cc runtime. The pod configuration is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: enclave-pod
spec:
  containers:
  - name: sysbench-test
    image: sgx-fio222:1.0
    workingDir: "/run/rune/occlum_instance/"
    resources:
      limits:
        sgx.intel.com/epc: 105Mi
    env:
    - name: OCCLUM_RELEASE_ENCLAVE
      value: "1"
    command:
    - /run/rune/occlum_instance/build/bin/occlum-run
    - /bin/fio
    - /bin/fio-seq-read.fio
  runtimeClassName: enclave-cc
```
For the parameters in the fio-seq-read.fio file, I reduced them as much as possible as follows:
```
[global]
name=fio-seq-read
filename=/root/fio-seq-read
rw=read
bs=32K
direct=1
numjobs=1
time_based
runtime=30

[file1]
size=32M
ioengine=sync
iodepth=1
```
The container starts successfully, but it throws the following error during execution:

![Image](https://github.com/user-attachments/assets/a13ab2ea-339d-4c7d-bb95-55663f0088c5)
